name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: build-artifact
        path: dist/
        if-no-files-found: warn
        retention-days: 7
        compression-level: 6
        overwrite: false
        include-hidden-files: false
